# Generated by Django 5.2.16 on 2026-07-30 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeErreur',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('definition', models.TextField(verbose_name='définition')),
                ('signature', models.TextField(verbose_name='signature observable sur la copie')),
                ('exemple', models.TextField(blank=True, verbose_name='exemple concret')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='coefficient de coût')),
                ('remediable', models.BooleanField(verbose_name='donne lieu à remédiation')),
            ],
            options={
                'verbose_name': "type d'erreur",
                'verbose_name_plural': "types d'erreur",
                'ordering': ['-coefficient', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code canonique')),
                ('domaine', models.CharField(choices=[('Activites numeriques', 'Activités numériques'), ('Calcul litteral et algebre', 'Calcul littéral et algèbre'), ('Activites geometriques', 'Activités géométriques'), ('Mesures et grandeurs', 'Mesures et grandeurs'), ('Fonctions et applications', 'Fonctions et applications'), ('Donnees, proportionnalite, statistique', 'Données, proportionnalité, statistique'), ('Suites et raisonnement', 'Suites et raisonnement'), ('Trigonometrie', 'Trigonométrie')], max_length=60)),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('description', models.TextField(blank=True)),
                ('niveau_intro', models.CharField(max_length=20, verbose_name="niveau d'introduction")),
                ('chapitre_intro', models.CharField(blank=True, max_length=100, verbose_name="chapitre d'origine")),
                ('transversale', models.BooleanField(default=False)),
                ('volume_horaire', models.DecimalField(blank=True, decimal_places=2, help_text='Nul pour les 27 compétences du lycée : volume absent des documents officiels.', max_digits=5, null=True, verbose_name='volume horaire officiel (h)')),
                ('source_volume', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'compétence',
                'ordering': ['domaine', 'code'],
                'indexes': [models.Index(fields=['domaine'], name='referentiel_domaine_ae99ce_idx'), models.Index(fields=['niveau_intro'], name='referentiel_niveau__943f5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_question', models.CharField(max_length=10)),
                ('niveau_test', models.CharField(choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2ndeC', '2nde C'), ('1ereD', '1ère D'), ('tleD', 'Terminale D')], max_length=10)),
                ('partie', models.CharField(choices=[('A', 'Partie A — questions courtes'), ('B', 'Partie B — exercices rédigés')], max_length=1)),
                ('format', models.CharField(choices=[('qcm', 'QCM'), ('court', 'Réponse courte'), ('redige', 'Exercice rédigé'), ('construction', 'Construction géométrique')], max_length=15)),
                ('bareme', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='barème (sur 20)')),
                ('bareme_classeur', models.DecimalField(decimal_places=1, max_digits=4, verbose_name="barème d'origine (sur 60)")),
                ('code_local', models.CharField(blank=True, help_text='Code de la matrice du test — LOCAL à ce test, jamais une clé.', max_length=10)),
                ('objet', models.TextField(verbose_name='objet de la question')),
                ('reponse_attendue', models.TextField(blank=True, help_text="Lettre de l'option pour un QCM. Vide pour les 209 questions sans corrigé au classeur (arbitrage B).", verbose_name='réponse attendue')),
                ('solution', models.TextField(blank=True, verbose_name='démarche attendue')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='referentiel.competence')),
                ('competence_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions_secondaires', to='referentiel.competence')),
            ],
            options={
                'verbose_name': 'question',
                'ordering': ['niveau_test', 'partie', 'code_question'],
            },
        ),
        migrations.CreateModel(
            name='SignatureErreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_eleve', models.TextField(verbose_name="ce qu'on lit sur la copie")),
                ('interpretation', models.TextField(verbose_name='lacune révélée')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='referentiel.competence')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='referentiel.question')),
                ('type_erreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='referentiel.typeerreur')),
            ],
            options={
                'verbose_name': "signature d'erreur",
                'verbose_name_plural': "signatures d'erreur",
                'ordering': ['question', 'type_erreur'],
            },
        ),
        migrations.CreateModel(
            name='OptionQcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre', models.CharField(max_length=2)),
                ('texte', models.TextField()),
                ('correcte', models.BooleanField(default=False)),
                ('erreur', models.TextField(blank=True, verbose_name='erreur qui conduit à cette option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='referentiel.question')),
                ('type_erreur', models.ForeignKey(blank=True, help_text='Nul pour la bonne réponse : elle ne révèle aucune erreur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='options', to='referentiel.typeerreur')),
            ],
            options={
                'verbose_name': 'option de QCM',
                'verbose_name_plural': 'options de QCM',
                'ordering': ['question', 'lettre'],
            },
        ),
        migrations.CreateModel(
            name='CoutRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_heures', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(4)], verbose_name='coût estimé (h)')),
                ('derivation', models.CharField(blank=True, help_text='Trace du calcul, reprise du classeur — ex. « 4e ch15 : 4 h / 2 = 2.0 h ».', max_length=200, verbose_name='dérivation du volume')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='referentiel.competence')),
                ('type_erreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts', to='referentiel.typeerreur')),
            ],
            options={
                'verbose_name': 'coût de remédiation',
                'verbose_name_plural': 'coûts de remédiation',
                'ordering': ['competence', '-cout_heures'],
            },
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='referentiel.competence')),
                ('prerequis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requis_par', to='referentiel.competence')),
            ],
            options={
                'verbose_name': 'prérequis',
                'verbose_name_plural': 'prérequis',
                'constraints': [models.UniqueConstraint(fields=('competence', 'prerequis'), name='prerequis_unique'), models.CheckConstraint(condition=models.Q(('competence', models.F('prerequis')), _negated=True), name='prerequis_pas_reflexif')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['niveau_test', 'partie'], name='referentiel_niveau__e4fb34_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['competence'], name='referentiel_compete_2f7a25_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('niveau_test', 'code_question'), name='question_unique_par_test'),
        ),
        migrations.AddIndex(
            model_name='signatureerreur',
            index=models.Index(fields=['type_erreur'], name='referentiel_type_er_b86f65_idx'),
        ),
        migrations.AddConstraint(
            model_name='optionqcm',
            constraint=models.UniqueConstraint(fields=('question', 'lettre'), name='option_unique_par_question'),
        ),
        migrations.AddConstraint(
            model_name='optionqcm',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correcte', True), ('type_erreur__isnull', True)), models.Q(('correcte', False), ('type_erreur__isnull', False)), _connector='OR'), name='option_type_erreur_coherent'),
        ),
        migrations.AddConstraint(
            model_name='coutremediation',
            constraint=models.UniqueConstraint(fields=('competence', 'type_erreur'), name='cout_unique_par_couple'),
        ),
    ]
