# Generated by Django 5.2.16 on 2026-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='volume_estime',
            field=models.BooleanField(default=False, help_text='Vrai quand le volume est une valeur de repli et non un chiffre officiel — le cas des 27 compétences de lycée. Voir referentiel/couts.py.', verbose_name='volume estimé'),
        ),
        migrations.AddField(
            model_name='coutremediation',
            name='estime',
            field=models.BooleanField(default=False, help_text="Vrai quand le coût dérive d'un volume de repli et non d'un volume officiel. À afficher comme tel : ce n'est pas une valeur du curriculum.", verbose_name='coût estimé'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='volume_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Officiel pour le collège. Valeur de repli pour le lycée, où les documents ne donnent pas de volume par chapitre — `volume_estime` le signale.', max_digits=5, null=True, verbose_name='volume horaire (h)'),
        ),
    ]
