# Generated by Django 5.2.16 on 2026-07-30 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('identifiant_hakili', models.CharField(db_index=True, max_length=255)),
                ('eleve_nom', models.CharField(blank=True, max_length=120)),
                ('eleve_prenom', models.CharField(blank=True, max_length=120)),
                ('bareme_id', models.CharField(blank=True, help_text='Test du catalogue, vide en mode libre.', max_length=60)),
                ('instructions_expert', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('creee', 'Créée'), ('transcription', 'Transcription en cours'), ('relecture', 'En attente de relecture de la transcription'), ('correction', 'Correction en cours'), ('validation', 'En attente de validation des notes'), ('diagnostic', 'Diagnostic en cours'), ('terminee', 'Terminée'), ('echec', 'Échec')], default='creee', max_length=15)),
                ('etape', models.CharField(blank=True, help_text='Libellé affiché.', max_length=120)),
                ('progression', models.PositiveSmallIntegerField(default=0)),
                ('resultat', models.JSONField(blank=True, null=True)),
                ('erreurs', models.JSONField(blank=True, default=list)),
                ('lancee_par', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'correction',
                'ordering': ['-cree_le'],
            },
        ),
    ]
