# Generated by Django 5.2.16 on 2026-07-30 11:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('copy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('identifiant_hakili', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=50)),
                ('annee_scolaire', models.CharField(max_length=50)),
                ('date_soumission', models.DateField()),
                ('notes_finales', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'copie (lecture seule)',
                'verbose_name_plural': 'copies (lecture seule)',
                'db_table': 'copie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('hypothese', 'Hypothèse — détecté, pas encore vérifié'), ('confirme', 'Confirmé — difficulté réelle, à traiter'), ('ecarte', "Écarté — c'était une étourderie"), ('en_remediation', 'En remédiation'), ('resolu', 'Résolu'), ('non_resolu', 'Non résolu'), ('regresse', 'Régressé — réapparu au contrôle'), ('clos', 'Clos — acquis durablement')], default='hypothese', max_length=15)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, help_text='Lu dans CoutRemediation. Vaut 0 pour ATT (non remédiable) et pour les compétences de lycée sans volume horaire — cas normaux.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coût estimé (h)')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problemes', to='referentiel.competence')),
                ('type_erreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problemes', to='referentiel.typeerreur')),
            ],
            options={
                'verbose_name': 'problème',
                'verbose_name_plural': 'problèmes',
                'ordering': ['session', '-cout_estime'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_hakili', models.CharField(db_index=True, help_text="Lien vers l'élève dans le Google Sheet. Jamais une clé étrangère — l'identité ne vit pas en base (D-CEO-20).", max_length=255)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('palier', models.CharField(blank=True, choices=[('A', 'A — ciblé (moins de 8 h, 2 à 4 séances, sans T2)'), ('B', 'B — complet (8 à 20 h, déroulé intégral)'), ('C', 'C — hors dispositif (plus de 20 h)')], help_text="Vide jusqu'à T1 : le palier découle du coût des problèmes confirmés.", max_length=1)),
                ('etat', models.CharField(choices=[('ouverte', 'Ouverte'), ('close', 'Close'), ('abandonnee', 'Abandonnée')], default='ouverte', max_length=12)),
                ('date_cloture', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'session',
                'db_table': 'session_urie',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('date_cloture__isnull', True), ('etat', 'ouverte')), models.Q(('etat', 'ouverte'), _negated=True), _connector='OR'), name='session_ouverte_sans_date_cloture')],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('tuteur', models.CharField(max_length=120)),
                ('duree', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée (min)')),
                ('blocage', models.TextField(blank=True, verbose_name='ce qui a bloqué')),
                ('deblocage', models.TextField(blank=True, verbose_name='ce qui a débloqué')),
                ('travail_donne', models.TextField(blank=True, verbose_name='travail donné')),
                ('appreciation', models.TextField(blank=True, verbose_name='appréciation de la séance')),
                ('problemes_travailles', models.ManyToManyField(blank=True, help_text='À choisir parmi les problèmes ouverts de la session.', related_name='seances', to='suivi.probleme')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='suivi.session')),
            ],
            options={
                'verbose_name': 'séance',
                'verbose_name_plural': 'séances',
                'ordering': ['session', '-date'],
            },
        ),
        migrations.AddField(
            model_name='probleme',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes', to='suivi.session'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T0', 'T0 — positionnement (1 h 30)'), ('T1', 'T1 — confirmation (45 min)'), ('T2', 'T2 — progression (1 h)'), ('T3', 'T3 — sortie (1 h 15)'), ('T4', 'T4 — consolidation à 45 jours'), ('T5', 'T5 — consolidation à 3 mois')], max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('duree_reelle', models.PositiveIntegerField(blank=True, help_text="Alimente l'indicateur d'écart durée estimée / réelle (module 9).", null=True, verbose_name='durée réelle (min)')),
                ('support', models.CharField(blank=True, help_text='Ex. « scan 150 DPI », « saisie manuelle ».', max_length=50)),
                ('copy_id', models.CharField(blank=True, db_index=True, help_text="Identifiant de la copie déjà persistée par le pipeline. Vide si l'évaluation a été saisie à la main.", max_length=255, verbose_name='copie associée')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='suivi.session')),
            ],
            options={
                'verbose_name': 'évaluation',
                'ordering': ['session', 'date', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_avant', models.CharField(choices=[('hypothese', 'Hypothèse — détecté, pas encore vérifié'), ('confirme', 'Confirmé — difficulté réelle, à traiter'), ('ecarte', "Écarté — c'était une étourderie"), ('en_remediation', 'En remédiation'), ('resolu', 'Résolu'), ('non_resolu', 'Non résolu'), ('regresse', 'Régressé — réapparu au contrôle'), ('clos', 'Clos — acquis durablement')], max_length=15)),
                ('etat_apres', models.CharField(choices=[('hypothese', 'Hypothèse — détecté, pas encore vérifié'), ('confirme', 'Confirmé — difficulté réelle, à traiter'), ('ecarte', "Écarté — c'était une étourderie"), ('en_remediation', 'En remédiation'), ('resolu', 'Résolu'), ('non_resolu', 'Non résolu'), ('regresse', 'Régressé — réapparu au contrôle'), ('clos', 'Clos — acquis durablement')], max_length=15)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(blank=True, help_text="L'évaluation qui a provoqué le changement, quand il y en a une.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='suivi.evaluation')),
                ('probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='suivi.probleme')),
            ],
            options={
                'verbose_name': 'transition',
                'ordering': ['probleme', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_brute', models.TextField(blank=True, help_text='Transcription de la copie. Vide = sans réponse.')),
                ('correcte', models.BooleanField(blank=True, help_text='Nul = pas encore corrigé.', null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='suivi.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='referentiel.question')),
                ('type_erreur_detecte', models.ForeignKey(blank=True, db_column='code_type_erreur_detecte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='referentiel.typeerreur')),
            ],
            options={
                'verbose_name': 'réponse',
                'ordering': ['evaluation', 'question'],
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'question'), name='reponse_unique_par_evaluation'), models.CheckConstraint(condition=models.Q(('correcte', True), ('type_erreur_detecte__isnull', False), _negated=True), name='reponse_juste_sans_type_erreur')],
            },
        ),
        migrations.AddConstraint(
            model_name='probleme',
            constraint=models.UniqueConstraint(fields=('session', 'competence', 'type_erreur'), name='probleme_unique_par_session'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('session', 'type'), name='evaluation_unique_par_session'),
        ),
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['etat_apres', 'date'], name='suivi_trans_etat_ap_9aa138_idx'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.CheckConstraint(condition=models.Q(('etat_avant', models.F('etat_apres')), _negated=True), name='transition_change_etat'),
        ),
    ]
