# Generated by Django 5.2.16 on 2026-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_alter_evaluation_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='session_ouverte_sans_date_cloture',
        ),
        migrations.AddField(
            model_name='session',
            name='date_inscription',
            field=models.DateField(blank=True, help_text="Entrée officielle en remédiation. C'est de cette date que part le décompte du volume horaire — et vraisemblablement la facturation.", null=True, verbose_name="date d'inscription au programme"),
        ),
        migrations.AlterField(
            model_name='session',
            name='etat',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic en cours (T0, T1)'), ('attente_inscription', "Plan établi — en attente d'inscription"), ('remediation', 'Inscrit en remédiation'), ('close', 'Cycle clos'), ('sans_suite', 'Sortie sans remédiation — aucune lacune confirmée'), ('hors_dispositif', 'Orienté hors dispositif (palier C)'), ('abandonnee', 'Abandonnée')], default='diagnostic', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('etat__in', ['hors_dispositif', 'close', 'abandonnee', 'sans_suite']), ('date_cloture__isnull', True), _connector='OR'), name='session_en_cours_sans_date_cloture'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date_inscription__isnull', False), ('etat', 'remediation')), models.Q(('etat', 'remediation'), _negated=True), _connector='OR'), name='remediation_implique_date_inscription'),
        ),
    ]
