# Generated by Django 5.2.16 on 2026-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_remove_session_session_ouverte_sans_date_cloture_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='session_en_cours_sans_date_cloture',
        ),
        migrations.AlterField(
            model_name='session',
            name='palier',
            field=models.CharField(blank=True, choices=[('A', 'A — ciblé (moins de 8 h, 2 à 4 séances)'), ('B', 'B — complet (8 à 20 h)'), ('C', 'C — hors dispositif (plus de 20 h)')], help_text="Vide jusqu'à T1 : le palier découle du coût des problèmes confirmés.", max_length=1),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('etat__in', ['sans_suite', 'abandonnee', 'hors_dispositif', 'close']), ('date_cloture__isnull', True), _connector='OR'), name='session_en_cours_sans_date_cloture'),
        ),
    ]
