# Generated by Django 5.2.16 on 2026-07-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0004_remove_session_session_en_cours_sans_date_cloture_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='session_en_cours_sans_date_cloture',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='corpus_reference',
            field=models.BooleanField(db_index=True, default=False, help_text='Les problèmes de cette évaluation ont été relevés par un humain et font foi. Le module 4 se mesure contre eux, il ne les écrase jamais.', verbose_name='copie du corpus de référence'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='date_tagage',
            field=models.DateField(blank=True, null=True, verbose_name='date du relevé'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='tague_par',
            field=models.CharField(blank=True, help_text="Qui a fait le relevé. Un corpus sans auteur n'est pas discutable : deux personnes ne tagueront pas tout à fait pareil, et c'est une information, pas un défaut.", max_length=120, verbose_name='tagué par'),
        ),
        migrations.AddField(
            model_name='probleme',
            name='evaluation_origine',
            field=models.ForeignKey(blank=True, help_text='La passation qui a fait apparaître ce problème. Nul pour un problème saisi hors évaluation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemes_reveles', to='suivi.evaluation', verbose_name='révélé par'),
        ),
        migrations.AddField(
            model_name='probleme',
            name='justification',
            field=models.TextField(blank=True, help_text="La production de l'élève qui a conduit à relever ce problème. Saisie à la main pour le corpus de référence (module 3), remplie par la citation du diagnostic pour le module 4 — c'est ce qui rend un désaccord entre les deux arbitrable plutôt qu'un simple écart de comptage.", verbose_name='ce qui a été lu sur la copie'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(condition=models.Q(('corpus_reference', False), models.Q(models.Q(('tague_par', ''), _negated=True), ('date_tagage__isnull', False)), _connector='OR'), name='corpus_reference_trace'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('etat__in', ['abandonnee', 'close', 'hors_dispositif', 'sans_suite']), ('date_cloture__isnull', True), _connector='OR'), name='session_en_cours_sans_date_cloture'),
        ),
    ]
