# Generated by Django 5.2.16 on 2026-07-31 12:35

from django.db import migrations, models


def marquer_sessions_existantes(apps, schema_editor):
    """Reprend les sessions taguées avant l'existence du drapeau.

    Les premières copies du corpus ont créé des sessions ordinaires. Sans cette
    reprise, elles passeraient désormais pour du suivi réel : le tagage les
    refuserait, et rien n'empêcherait leurs problèmes d'entrer dans un calcul de
    palier. Une session est de corpus dès qu'elle porte une évaluation de corpus.
    """
    Session = apps.get_model("suivi", "Session")
    Session.objects.filter(evaluations__corpus_reference=True).distinct().update(
        corpus_reference=True
    )


def demarquer(apps, schema_editor):
    apps.get_model("suivi", "Session").objects.update(corpus_reference=False)


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0005_corpus_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='corpus_reference',
            field=models.BooleanField(db_index=True, default=False, help_text="Session ouverte pour taguer une copie du corpus (module 3). Ce n'est pas le parcours d'un élève : elle ne peut ni établir de plan ni inscrire au programme.", verbose_name='session du corpus de référence'),
        ),
        migrations.RunPython(marquer_sessions_existantes, demarquer),
    ]
