# Generated by Django 5.2.17 on 2026-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0007_copie_document_sous_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('scan', 'scan'), ('rapport', 'rapport'), ('sujet_confirmation', 'sujet de confirmation (T1)'), ('remediation', 'remédiation')], max_length=50),
        ),
    ]
