# Generated by Django 5.2.17 on 2026-08-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0008_alter_document_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='session',
            table='session_suivi',
        ),
    ]
